version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest  
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'  
        nginx['listen_port'] = 8929                   
        nginx['listen_https'] = false                 
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - 'gl-config:/etc/gitlab'
      - 'gl-logs:/var/log/gitlab'
      - 'gl-data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab-network

volumes:
  gl-config:
  gl-logs:
  gl-data:

networks:
  gitlab-network:
    name: gitlab-network
