networks:
  default:
    name: 'tfa'
  
volumes: 
  tfa-logs:
  
services:

  opensearch:
    container_name: 'tfa-os'
    image: 'opensearchproject/opensearch:latest'
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      discovery.type: 'single-node'
      plugins.security.disabled: 'true'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'Vladikpav_2002'
    volumes:
      - tfa-logs:/usr/share/opensearch/data
      
  opensearch-dashboards:
    container_name: 'tfa-osd'
    image: 'opensearchproject/opensearch-dashboards:latest'
    ports:
      - '5601:5601'
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS: 'true'
    depends_on: 
      - opensearch