networks:
  default:
    name: 'tfa'
  
volumes: 
  tfa-logs:
  tfa-prom:
  tfa-grafana:
  
services:

  opensearch:
    container_name: 'tfa-os'
    image: 'opensearchproject/opensearch:latest'
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      discovery.type: 'single-node'
      plugins.security.disabled: 'true'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'Vladikpav_2002'
    volumes:
      - tfa-logs:/usr/share/opensearch/data
      
  opensearch-dashboards:
    container_name: 'tfa-osd'
    image: 'opensearchproject/opensearch-dashboards:latest'
    ports:
      - '5601:5601'
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS: 'true'
    depends_on: 
      - opensearch

  prometheus:
    container_name: 'tfa-prom'
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - tfa-prom:/prometheus
        
  grafana:
    container_name: 'tfa-grafana'
    image: 'grafana/grafana'
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel, grafana-simple-json-datasource'
    volumes:
      - tfa-grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
